import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
			   
			  int two =0;
			  int three =0; 
			  int four =0;
		
			for (int i=0; i<T ; i++){
				 int count = 0; 
				 int g =0;
				 int b = 0;
			   
			 while (!((g>=1) && (b>=1))) {
				double num = generator.nextDouble();
				   if (num>0.5) {
					   g++;
					   count++;
				  } else {
					   b++;
					   count++;
					}
				}
			   
				if (count==2) {
					two++ ; 
				 } else { if (count== 3) {
					three++ ; 
				 } else {
					four++ ;
			  }
			   }
		
				 }
				 double avr = ((two*2.0+three*3.0+four*4.0)/ T);
				 System.out.println("Average: " + avr + " children to get at least one of each gender.");
		
				 System.out.println("Number of families with 2 children: " + two );
				 System.out.println("Number of families with 3 children: " + three );
				 System.out.println("Number of families with 4 children: " + four );
				 
				 if ((two>three)&&(two>four)){
					System.out.println("The most comon nymber of children is 2." );   
				   } else { if ((three>two)&& (three>four)) {
					System.out.println("The most comon nymber of children is 3." ); 
				   } else {
					  System.out.println("The most comon nymber of children is 4 or more." ); 
				   }
				   }
			}
		
		   }  
